name: Tests

on: [push, pull_request]

env:
  CI: true
  COREPACK_INTEGRITY_KEYS: 0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 24

      - name: Enable corepack (for pnpm)
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build coverage addon
        run: pnpm build

      - name: Run tests in webpack example
        run: |
          pnpm install --frozen-lockfile
          npx playwright install --with-deps
          pnpm test-storybook:ci-coverage
        working-directory: examples/webpack5

      - name: Run tests in vite example
        run: |
          pnpm install --frozen-lockfile
          npx playwright install --with-deps
          pnpm test-storybook:ci-coverage
        working-directory: examples/vite
